import type { AnalysisResult } from "./types";

export const PRACTICE_DATA: AnalysisResult = {
    title: "新聞採訪與隱私 (News Interview & Privacy)",
    sections: [
        {
            speaker: "測試 (Warm-up)",
            sentences: [
                {
                    id: "test-1",
                    original: "窺探他人隱私的心理，是與生俱來的。",
                    tokens: [
                        { hanzi: "窺探", pinyin: "kuī tàn" },
                        { hanzi: "他人", pinyin: "tā rén" },
                        { hanzi: "隱私", pinyin: "yǐn sī" },
                        { hanzi: "的", pinyin: "de" },
                        { hanzi: "心理", pinyin: "xīn lǐ" },
                        { hanzi: "，", pinyin: "" },
                        { hanzi: "是", pinyin: "shì" },
                        { hanzi: "與生俱來", pinyin: "yǔ shēng jù lái" },
                        { hanzi: "的", pinyin: "de" },
                        { hanzi: "。", pinyin: "" }
                    ]
                }
            ]
        },
        {
            speaker: "莊雅玲 (Zhuang Yaling)",
            sentences: [
                {
                    id: "zyl-1",
                    original: "窺探他人隱私的心理，是與生俱來的。前兩天的報道就是很好的證明，市民的投訴破了紀錄，週刊銷量卻大增，雜誌社竟然在一片譴責聲中還加印出售，這不就是迎合大眾口味的市場導向在起作用嘛。不過，從好的一方面來看，我倒覺得香港記者能做這種圍攻式追訪，正顯示他們享有相當大的採訪自由。",
                    tokens: [
                        { hanzi: "窺探", pinyin: "kuī tàn" },
                        { hanzi: "他人", pinyin: "tā rén" },
                        { hanzi: "隱私", pinyin: "yǐn sī" },
                        { hanzi: "的", pinyin: "de" },
                        { hanzi: "心理", pinyin: "xīn lǐ" },
                        { hanzi: "，", pinyin: "" },
                        { hanzi: "是", pinyin: "shì" },
                        { hanzi: "與生俱來", pinyin: "yǔ shēng jù lái" },
                        { hanzi: "的", pinyin: "de" },
                        { hanzi: "。", pinyin: "" },
                        { hanzi: "前兩天", pinyin: "qián liǎng tiān" },
                        { hanzi: "的", pinyin: "de" },
                        { hanzi: "報道", pinyin: "bào dào" },
                        { hanzi: "就是", pinyin: "jiù shì" },
                        { hanzi: "很", pinyin: "hěn" },
                        { hanzi: "好", pinyin: "hǎo" },
                        { hanzi: "的", pinyin: "de" },
                        { hanzi: "證明", pinyin: "zhèng míng" },
                        { hanzi: "，", pinyin: "" },
                        { hanzi: "市民", pinyin: "shì mín" },
                        { hanzi: "的", pinyin: "de" },
                        { hanzi: "投訴", pinyin: "tóu sù" },
                        { hanzi: "破了", pinyin: "pò le" },
                        { hanzi: "紀錄", pinyin: "jì lù" },
                        { hanzi: "，", pinyin: "" },
                        { hanzi: "週刊", pinyin: "zhōu kān" },
                        { hanzi: "銷量", pinyin: "xiāo liàng" },
                        { hanzi: "卻", pinyin: "què" },
                        { hanzi: "大增", pinyin: "dà zēng" },
                        { hanzi: "，", pinyin: "" },
                        { hanzi: "雜誌社", pinyin: "zá zhì shè" },
                        { hanzi: "竟然", pinyin: "jìng rán" },
                        { hanzi: "在", pinyin: "zài" },
                        { hanzi: "一片", pinyin: "yí piàn" },
                        { hanzi: "譴責", pinyin: "qiǎn zé" },
                        { hanzi: "聲中", pinyin: "shēng zhōng" },
                        { hanzi: "還", pinyin: "hái" },
                        { hanzi: "加印", pinyin: "jiā yìn" },
                        { hanzi: "出售", pinyin: "chū shòu" },
                        { hanzi: "，", pinyin: "" },
                        { hanzi: "這", pinyin: "zhè" },
                        { hanzi: "不就是", pinyin: "bú jiù shì" },
                        { hanzi: "迎合", pinyin: "yíng hé" },
                        { hanzi: "大眾", pinyin: "dà zhòng" },
                        { hanzi: "口味", pinyin: "kǒu wèi" },
                        { hanzi: "的", pinyin: "de" },
                        { hanzi: "市場", pinyin: "shì chǎng" },
                        { hanzi: "導向", pinyin: "dǎo xiàng" },
                        { hanzi: "在", pinyin: "zài" },
                        { hanzi: "起作用", pinyin: "qǐ zuò yòng" },
                        { hanzi: "嘛", pinyin: "ma" },
                        { hanzi: "。", pinyin: "" },
                        { hanzi: "不過", pinyin: "bú guò" },
                        { hanzi: "，", pinyin: "" },
                        { hanzi: "從", pinyin: "cóng" },
                        { hanzi: "好的一方面", pinyin: "hǎo de yì fāng miàn" },
                        { hanzi: "來看", pinyin: "lái kàn" },
                        { hanzi: "，", pinyin: "" },
                        { hanzi: "我倒覺得", pinyin: "wǒ dào jué de" },
                        { hanzi: "香港", pinyin: "xiāng gǎng" },
                        { hanzi: "記者", pinyin: "jì zhě" },
                        { hanzi: "能", pinyin: "néng" },
                        { hanzi: "做", pinyin: "zuò" },
                        { hanzi: "這種", pinyin: "zhè zhǒng" },
                        { hanzi: "圍攻式", pinyin: "wéi gōng shì" },
                        { hanzi: "追訪", pinyin: "zhuī fǎng" },
                        { hanzi: "，", pinyin: "" },
                        { hanzi: "正", pinyin: "zhèng" },
                        { hanzi: "顯示", pinyin: "xiǎn shì" },
                        { hanzi: "他們", pinyin: "tā men" },
                        { hanzi: "享有", pinyin: "xiǎng yǒu" },
                        { hanzi: "相當大", pinyin: "xiāng dāng dà" },
                        { hanzi: "的", pinyin: "de" },
                        { hanzi: "採訪", pinyin: "cǎi fǎng" },
                        { hanzi: "自由", pinyin: "zì yóu" },
                        { hanzi: "。", pinyin: "" }
                    ]
                }
            ]
        },
        {
            speaker: "沈藝欣 (Shen Yixin) - Part 1",
            sentences: [
                {
                    id: "syx-1",
                    original: "是啊，身為記者應該珍惜這樣的自由，而不是濫用。我有時也會採用偷拍偷錄的辦法來取得一些新聞素材，那是為了防止接受採訪的人弄虛作假，如果不把那些不合情理，甚至不合法的事情如實報道出來，就不能發揮輿論的監督作用。",
                    tokens: [
                        { hanzi: "是啊", pinyin: "shì a" },
                        { hanzi: "，", pinyin: "" },
                        { hanzi: "身為", pinyin: "shēn wéi" },
                        { hanzi: "記者", pinyin: "jì zhě" },
                        { hanzi: "應該", pinyin: "yīng gāi" },
                        { hanzi: "珍惜", pinyin: "zhēn xī" },
                        { hanzi: "這樣", pinyin: "zhè yàng" },
                        { hanzi: "的", pinyin: "de" },
                        { hanzi: "自由", pinyin: "zì yóu" },
                        { hanzi: "，", pinyin: "" },
                        { hanzi: "而", pinyin: "ér" },
                        { hanzi: "不是", pinyin: "bú shì" },
                        { hanzi: "濫用", pinyin: "làn yòng" },
                        { hanzi: "。", pinyin: "" },
                        { hanzi: "我", pinyin: "wǒ" },
                        { hanzi: "有時", pinyin: "yǒu shí" },
                        { hanzi: "也會", pinyin: "yě huì" },
                        { hanzi: "採用", pinyin: "cǎi yòng" },
                        { hanzi: "偷拍", pinyin: "tōu pāi" },
                        { hanzi: "偷錄", pinyin: "tōu lù" },
                        { hanzi: "的", pinyin: "de" },
                        { hanzi: "辦法", pinyin: "bàn fǎ" },
                        { hanzi: "來", pinyin: "lái" },
                        { hanzi: "取得", pinyin: "qǔ dé" },
                        { hanzi: "一些", pinyin: "yì xiē" },
                        { hanzi: "新聞", pinyin: "xīn wén" },
                        { hanzi: "素材", pinyin: "sù cái" },
                        { hanzi: "，", pinyin: "" },
                        { hanzi: "那", pinyin: "nà" },
                        { hanzi: "是", pinyin: "shì" },
                        { hanzi: "為了", pinyin: "wèi le" },
                        { hanzi: "防止", pinyin: "fáng zhǐ" },
                        { hanzi: "接受", pinyin: "jiē shòu" },
                        { hanzi: "採訪", pinyin: "cǎi fǎng" },
                        { hanzi: "的", pinyin: "de" },
                        { hanzi: "人", pinyin: "rén" },
                        { hanzi: "弄虛作假", pinyin: "nòng xū zuò jiǎ" },
                        { hanzi: "，", pinyin: "" },
                        { hanzi: "如果", pinyin: "rú guǒ" },
                        { hanzi: "不", pinyin: "bù" },
                        { hanzi: "把", pinyin: "bǎ" },
                        { hanzi: "那些", pinyin: "nà xiē" },
                        { hanzi: "不合情理", pinyin: "bù hé qíng lǐ" },
                        { hanzi: "，", pinyin: "" },
                        { hanzi: "甚至", pinyin: "shèn zhì" },
                        { hanzi: "不合法", pinyin: "bù hé fǎ" },
                        { hanzi: "的", pinyin: "de" },
                        { hanzi: "事情", pinyin: "shì qíng" },
                        { hanzi: "如實", pinyin: "rú shí" },
                        { hanzi: "報道", pinyin: "bào dào" },
                        { hanzi: "出來", pinyin: "chū lái" },
                        { hanzi: "，", pinyin: "" },
                        { hanzi: "就", pinyin: "jiù" },
                        { hanzi: "不能", pinyin: "bù néng" },
                        { hanzi: "發揮", pinyin: "fā huī" },
                        { hanzi: "輿論", pinyin: "yú lùn" },
                        { hanzi: "的", pinyin: "de" },
                        { hanzi: "監督", pinyin: "jiān dū" },
                        { hanzi: "作用", pinyin: "zuò yòng" },
                        { hanzi: "。", pinyin: "" }
                    ]
                }
            ]
        },
        {
            speaker: "沈藝欣 (Shen Yixin) - Part 2",
            sentences: [
                {
                    id: "syx-2",
                    original: "不過說到底，這也只能限於針對某一個具體的採訪題材，而並非毫無限制，漁翁撒網式地來找新聞。英國的《世界新聞報》這次的竊聽風波之所以讓傳媒大亨默多克栽了個大跟頭，就是因為這種不顧法律底線和道德邊界的採訪行為已經超出了社會的容忍範圍。",
                    tokens: [
                        { hanzi: "不過", pinyin: "bú guò" },
                        { hanzi: "說到底", pinyin: "shuō dào dǐ" },
                        { hanzi: "，", pinyin: "" },
                        { hanzi: "這", pinyin: "zhè" },
                        { hanzi: "也", pinyin: "yě" },
                        { hanzi: "只能", pinyin: "zhǐ néng" },
                        { hanzi: "限於", pinyin: "xiàn yú" },
                        { hanzi: "針對", pinyin: "zhēn duì" },
                        { hanzi: "某", pinyin: "mǒu" },
                        { hanzi: "一個", pinyin: "yí gè" },
                        { hanzi: "具體", pinyin: "jù tǐ" },
                        { hanzi: "的", pinyin: "de" },
                        { hanzi: "採訪", pinyin: "cǎi fǎng" },
                        { hanzi: "題材", pinyin: "tí cái" },
                        { hanzi: "，", pinyin: "" },
                        { hanzi: "而", pinyin: "ér" },
                        { hanzi: "並非", pinyin: "bìng fēi" },
                        { hanzi: "毫無限制", pinyin: "háo wú xiàn zhì" },
                        { hanzi: "，", pinyin: "" },
                        { hanzi: "漁翁撒網式", pinyin: "yú wēng sā wǎng shì" },
                        { hanzi: "地", pinyin: "de" },
                        { hanzi: "來", pinyin: "lái" },
                        { hanzi: "找", pinyin: "zhǎo" },
                        { hanzi: "新聞", pinyin: "xīn wén" },
                        { hanzi: "。", pinyin: "" },
                        { hanzi: "英國", pinyin: "yīng guó" },
                        { hanzi: "的", pinyin: "de" },
                        { hanzi: "《", pinyin: "" },
                        { hanzi: "世界新聞報", pinyin: "shì jiè xīn wén bào" },
                        { hanzi: "》", pinyin: "" },
                        { hanzi: "這次", pinyin: "zhè cì" },
                        { hanzi: "的", pinyin: "de" },
                        { hanzi: "竊聽", pinyin: "qiè tīng" },
                        { hanzi: "風波", pinyin: "fēng bō" },
                        { hanzi: "之所以", pinyin: "zhī suǒ yǐ" },
                        { hanzi: "讓", pinyin: "ràng" },
                        { hanzi: "傳媒", pinyin: "chuán méi" },
                        { hanzi: "大亨", pinyin: "dà hēng" },
                        { hanzi: "默多克", pinyin: "mò duō kè" },
                        { hanzi: "栽了個", pinyin: "zāi le ge" },
                        { hanzi: "大跟頭", pinyin: "dà gēn tou" },
                        { hanzi: "，", pinyin: "" },
                        { hanzi: "就是", pinyin: "jiù shì" },
                        { hanzi: "因為", pinyin: "yīn wèi" },
                        { hanzi: "這種", pinyin: "zhè zhǒng" },
                        { hanzi: "不顧", pinyin: "bú gù" },
                        { hanzi: "法律", pinyin: "fǎ lǜ" },
                        { hanzi: "底線", pinyin: "dǐ xiàn" },
                        { hanzi: "和", pinyin: "hé" },
                        { hanzi: "道德", pinyin: "dào dé" },
                        { hanzi: "邊界", pinyin: "biān jiè" },
                        { hanzi: "的", pinyin: "de" },
                        { hanzi: "採訪", pinyin: "cǎi fǎng" },
                        { hanzi: "行為", pinyin: "xíng wéi" },
                        { hanzi: "已經", pinyin: "yǐ jīng" },
                        { hanzi: "超出", pinyin: "chāo chū" },
                        { hanzi: "了", pinyin: "le" },
                        { hanzi: "社會", pinyin: "shè huì" },
                        { hanzi: "的", pinyin: "de" },
                        { hanzi: "容忍", pinyin: "róng rěn" },
                        { hanzi: "範圍", pinyin: "fàn wéi" },
                        { hanzi: "。", pinyin: "" }
                    ]
                }
            ]
        }
    ]
};

export const AZURE_CONFIG = {
    key: import.meta.env.VITE_SPEECH_KEY,
    region: import.meta.env.VITE_SPEECH_REGION
};
